apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: peerpodvolumes.confidentialcontainers.org
spec:
  group: confidentialcontainers.org
  names:
    kind: PeerpodVolume
    singular: peerpodvolume
    plural: peerpodvolumes
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                podName:
                  type: string
                podNamespace:
                  type: string
                podUid:
                  type: string
                nodeID:
                  type: string
                nodeName:
                  type: string
                volumeID:
                  type: string
                volumeName:
                  type: string
                vmID:
                  type: string
                vmName:
                  type: string
                devicePath:
                  type: string
                stagingTargetPath:
                  type: string
                targetPath:
                  type: string
                wrapperControllerPublishVolumeReq:
                  type: string
                wrapperControllerPublishVolumeRes:
                  type: string
                wrapperNodeStageVolumeReq:
                  type: string
                wrapperNodePublishVolumeReq:
                  type: string
            status:
              type: object
              properties:
                state:
                  type: string
      subresources:
        status: {}
