# permissions for end users to view peerpods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: peerpod-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: peerpod-ctrl
    app.kubernetes.io/part-of: peerpod-ctrl
    app.kubernetes.io/managed-by: kustomize
  name: peerpod-viewer-role
rules:
- apiGroups:
  - confidentialcontainers.org
  resources:
  - peerpods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - confidentialcontainers.org
  resources:
  - peerpods/status
  verbs:
  - get
