#
# (C) Copyright IBM Corp. 2022.
# SPDX-License-Identifier: Apache-2.0
#
---
- hosts: all
  remote_user: root
  tasks:
    - name: Get Kubernetes worker architecture
      shell:
        cmd: uname -m
      register: k8s_worker_architecture
    - name: Create Kubernetes resources for the nginx in peer pod demo
      shell:
        cmd: kubectl apply -f runtime-class.yaml -f nginx.yaml
        chdir: cloud-api-adaptor/ibmcloud/demo
    - name: Wait for pod to be ready
      shell:
        cmd: kubectl wait --timeout=300s --for=condition=ready pods/nginx
    - name: Check nginx container has started in the peer pod
      shell:
        cmd: kubectl get pod nginx -o json | jq -r .status.containerStatuses[0].ready
      register: nginx_container_ready
      failed_when: nginx_container_ready.stdout != 'true'
    - name: Send HTTP request to nginx container
      get_url:
        url: http://localhost:30080
        dest: /tmp/nginx.html
    - name: Delete the HTML document retrieved from nginx
      file:
        path: /tmp/nginx.html
        state: absent
    - name: Check peer pod VM architecture against the Kubernetes worker architecture
      shell:
        cmd: kubectl exec nginx -- uname -m
      register: peer_pod_architecture
      failed_when: peer_pod_architecture.stdout != k8s_worker_architecture.stdout
    - name: Check mounted volume from configMap
      shell:
        cmd: kubectl exec nginx -- cat /etc/config/example.txt
      register: volume_configmap_mounted
      failed_when: volume_configmap_mounted.stdout != 'Hello, world'
    - name: Check mounted volume from secret - username
      shell:
        cmd: kubectl exec nginx -- cat /etc/secret/username
      register: volume_secret_mounted_username
      failed_when: volume_secret_mounted_username.stdout != 'admin'
    - name: Check mounted volume from secret - password
      shell:
        cmd: kubectl exec nginx -- cat /etc/secret/password
      register: volume_secret_mounted_password
      failed_when: volume_secret_mounted_password.stdout != '123456'
