[Match]
Distribution=fedora
Profiles=gpu

[Content]
Packages=
   nvidia-container-toolkit
# 580.82.07: compatible with Fedora 42 kernel.
# See: https://github.com/NVIDIA/open-gpu-kernel-modules/pull/917
   nvidia-driver-cuda-580.82.07
   kmod-nvidia-open-dkms-580.82.07
