[Match]
Distribution=ubuntu

[Distribution]
Distribution=ubuntu
Release=noble

[Content]
CleanPackageMetadata=true
SkeletonTrees=../../resources/binaries-tree
Packages=
    linux-image-generic-hwe-24.04
    linux-headers-generic-hwe-24.04
    gcc
    make
    kmod
    udev
    util-linux
    systemd
    systemd-resolved
    dbus
    ca-certificates
    tpm2-tools
    iproute2
    iptables
    e2fsprogs
    cryptsetup
    nvidia-driver-580-open=580.126.20-1ubuntu1
    nvidia-persistenced=580.126.20-1ubuntu1
    nvidia-fabricmanager=580.126.20-1
    libnvidia-nscq=580.126.20-1
    nvidia-container-toolkit=1.19.0-1

RemoveFiles=/etc/issue
RemoveFiles=/etc/issue.net

# Strip build-time-only artifacts after DKMS compiles nvidia modules
RemoveFiles=/usr/src/linux-headers*
RemoveFiles=/usr/src/nvidia*

# Remove for reproducible builds
RemoveFiles=/var/log
RemoveFiles=/var/cache
