# Copyright (c) 2024 IBM Corporation
# SPDX-License-Identifier: Apache-2.0
#
# Configuration file with rules for the actionlint tool.
#
self-hosted-runner:
  # Labels of self-hosted runner that linter should ignore
  labels:
    - S390X
    - ubuntu-24.04-ppc64le
    - ubuntu-24.04-s390x

# Ignore until actionlint supports GitHub's $/ self-repository syntax (https://github.com/rhysd/actionlint/issues/711)
paths:
  .github/workflows/**/*.{yml,yaml}:
    ignore:
      - reusable workflow call "\$/.+" at "uses" is not following the format
      - specifying action "\$/.+" in invalid format because ref is missing
