# Copyright (c) 2024 IBM Corporation
# SPDX-License-Identifier: Apache-2.0
#
# Configuration file with rules for the actionlint tool.
#
self-hosted-runner:
  # Labels of self-hosted runner that linter should ignore
  labels:
    - S390X
