apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloud-api-adaptor-daemonset
  namespace: confidential-containers-system
  labels:
    app: cloud-api-adaptor
spec:
  template:
    spec:
      containers:
      - name: cloud-api-adaptor-con
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket
        - mountPath: /var/lib/docker
          name: docker-dir
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
      - name: docker-dir
        hostPath:
          path: /var/lib/docker

# to apply this uncomment the patchesStrategicMerge of this file in kustomization.yaml
