#
# (C) Copyright IBM Corp. 2023.
# SPDX-License-Identifier: Apache-2.0
#

---
- name: "Get containerd binary"
  unarchive:
    src: "https://github.com/containerd/containerd/releases/download/v{{ containerd_release_version }}/containerd-{{ containerd_release_version }}-linux-{{ ansible_architecture }}.tar.gz"
    dest: "/usr/local"
    remote_src: yes

- name: "Get runc binary"
  ansible.builtin.get_url:
    url: "https://github.com/opencontainers/runc/releases/download/v1.1.4/runc.{{ ansible_architecture }}"
    dest: /usr/local/sbin/runc
    mode: '0555'

- name: "Get cni plugin"
  unarchive:
    src: "https://github.com/containernetworking/plugins/releases/download/v1.2.0/cni-plugins-linux-{{ ansible_architecture }}-v1.2.0.tgz"
    dest: "/opt/cni/bin"
    remote_src: yes
