---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  - machineconfiguration.openshift.io
  resources:
  - configmaps
  - containerruntimeconfigs
  - endpoints
  - events
  - machineconfigpools
  - machineconfigs
  - nodes
  - persistentvolumeclaims
  - pods
  - secrets
  - services
  - services/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resourceNames:
  - peerpodconfig-ctrl-caa-daemon
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets/finalizers
  verbs:
  - update
- apiGroups:
  - confidentialcontainers.org
  resources:
  - peerpodconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - confidentialcontainers.org
  resources:
  - peerpodconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - confidentialcontainers.org
  resources:
  - peerpodconfigs/status
  verbs:
  - get
  - patch
  - update
