apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloud-api-adaptor-daemonset
  namespace: confidential-containers-system
  labels:
    app: cloud-api-adaptor
spec:
  template:
    spec:
      containers:
      - name: cloud-api-adaptor-con
        volumeMounts:
        - name: ssh
          mountPath: "/root/.ssh/"
          readOnly: true
      volumes:
      - name: ssh
        secret:
          secretName: ssh-key-secret
          defaultMode: 0600
          optional: true

# to apply this uncomment the patchesStrategicMerge of this file in kustomization.yaml
