#
# (C) Copyright IBM Corp. 2023.
# SPDX-License-Identifier: Apache-2.0
#

---
- name: "Add gpg key "
  apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v{{ kube_version }}/deb/Release.key
    state: present

- name: "Add kubernetes source list "
  apt_repository:
    repo: "deb https://pkgs.k8s.io/core:/stable:/v{{ kube_version }}/deb/ /"
    state: present
    filename: "kubernetes"

- name: "Install kubelet, kubeadm, kubectl "
  apt:
    update_cache: true
    name: ['kubelet', 'kubeadm', 'kubectl', 'kubernetes-cni', 'cri-tools']
    state: present
