apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azurefile
  namespace: kube-system
spec:
  storageClassName: azure-file-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
