#
# (C) Copyright IBM Corp. 2023.
# SPDX-License-Identifier: Apache-2.0
#

---
- hosts: all
  become: true
  vars:
    binaries_architecture: {
      "s390x": "s390x",
      "x86_64": "amd64"
    }
  tasks:
    - include_tasks: tasks/bootstrap.yaml
    - include_tasks: tasks/k8s.yaml
    - include_tasks: tasks/binaries.yaml

    - name: "Create a directory for containerd config"
      file: path=/etc/containerd state=directory

    - name: Load kernel modules
      modprobe:
        name: "{{ item }}"
      with_items:
        - br_netfilter

    - name: Set sysctl parameters for Kubernetes
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        reload: yes
      with_items:
        - { name: net.ipv4.ip_forward, value: 1 }
        - { name: net.bridge.bridge-nf-call-ip6tables, value: 1 }
        - { name: net.bridge.bridge-nf-call-iptables, value: 1 }

    - name: "Create a directory for systemd service"
      file: path=/usr/local/lib/systemd/system state=directory

    - name: "Get containerd.service"
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/containerd/containerd/main/containerd.service"
        dest: /usr/local/lib/systemd/system/containerd.service

    - name: "Start Containerd"
      systemd: name=containerd daemon_reload=yes state=started enabled=yes
