apiVersion: v1
kind: Pod
metadata:
  name: nginx-pv
  labels:
    app: nginx
  namespace: default
spec:
  runtimeClassName: kata-remote
  containers:
    - name: azure-file-podvm-node-driver
      env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      image: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.28.0
      imagePullPolicy: Always
      securityContext:
        privileged: true
        runAsNonRoot: false
        runAsUser: 0
      ports:
        - containerPort: 9808
          name: healthz
          protocol: TCP
      volumeMounts:
        - name: kubelet-data-dir
          mountPath: /var/lib/kubelet
          mountPropagation: Bidirectional
        - mountPath: /tmp
          name: plugin-dir
    - name: csi-podvm-wrapper
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAME_SPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: POD_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      args:
        - -v=2
        - --endpoint=/tmp/csi-podvm-wrapper.sock
        - --target-endpoint=/tmp/csi.sock
        - --namespace=kube-system
      image: quay.io/confidential-containers/csi-podvm-wrapper:latest
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /tmp
          name: plugin-dir
    - name: nginx
      image: nginx:stable
      imagePullPolicy: Always
      volumeMounts:
        - name: my-volume
          mountPath: /mount-path
          mountPropagation: HostToContainer
  serviceAccountName: csi-azurefile-podvm-sa
  volumes:
    - name: kubelet-data-dir
      hostPath:
        path: /var/lib/kubelet # OpenShift worker, for kubernetes /var/data/kubelet
        type: Directory
    - emptyDir: {}
      name: plugin-dir
    - name: my-volume
      persistentVolumeClaim:
        claimName: pvc-azurefile
