[Match]
Bootable=|auto
Bootable=|yes

[Output]
Format=cpio
Output=initrd

[Content]
MakeInitrd=yes
Bootable=no
Packages=systemd
         udev
         util-linux
         kmod
KernelInitrdModules=default
                    dm-mod
                    dm-bufio
                    dm-verity
                    dm-crypt
