---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resourceNames:
  - peer-pods-cm
  - peer-pods-secret
  resources:
  - configmaps
  - secrets
  verbs:
  - get
- apiGroups:
  - confidentialcontainers.org
  resources:
  - peerpods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - confidentialcontainers.org
  resources:
  - peerpods/finalizers
  verbs:
  - update
- apiGroups:
  - confidentialcontainers.org
  resources:
  - peerpods/status
  verbs:
  - get
  - patch
  - update
