apiVersion: v1
kind: ConfigMap
metadata:
  name: peer-pods-cm
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: peerpods
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  CLOUD_PROVIDER: "{{ .Values.provider }}"
{{- $config := index .Values.providerConfigs .Values.provider | default dict }}
{{- range $key, $value := $config }}
  {{ $key }}: "{{ $value }}"
{{- end }}
{{- if .Values.tlsProfile.minVersion }}
  TLS_MIN_VERSION: "{{ .Values.tlsProfile.minVersion }}"
{{- end }}
{{- if .Values.tlsProfile.cipherSuites }}
  TLS_CIPHER_SUITES: "{{ .Values.tlsProfile.cipherSuites }}"
{{- end }}
