# RBAC for PeerPods installer hook Job
#
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-peerpods-installer
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: peerpods
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: installer
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-peerpods-installer
  labels:
    app.kubernetes.io/name: peerpods
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: installer
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
# CRDs
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - create
  - update
  - patch
# ClusterRoles and ClusterRoleBindings
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - get
  - list
  - create
  - update
  - patch
# Roles and RoleBindings (in any namespace)
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - get
  - list
  - create
  - update
  - patch
# ServiceAccounts, Deployments, and Services
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - services
  verbs:
  - get
  - list
  - create
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - create
  - update
  - patch
# Namespaces (to create controller namespaces if needed)
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-peerpods-installer
  labels:
    app.kubernetes.io/name: peerpods
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: installer
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-peerpods-installer
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-peerpods-installer
  namespace: {{ .Values.namespace }}
