#!/usr/bin/env bash
# Copyright (c) Edgeless Systems GmbH
#
# SPDX-License-Identifier: Apache-2.0

# This script reads the measurements of the system
# and prints it together with helpful information
# to the serial consol on startup.

set -euo pipefail

main() {
  mkdir -p /run/issue.d
  /usr/bin/neofetch \
    --config /etc/neofetch/config.conf \
    --ascii /etc/neofetch/coco.ascii \
    --colors 9 9 9 9 9 12 \
    --ascii_colors 24 9 \
    > /run/issue.d/20-neofetch.issue
  {
    echo "Detected vTPM PCR values:"
    /usr/bin/tpm2_pcrread sha256:all
    echo
  } > /run/issue.d/30-pcrs.issue
}

main
