# syntax=docker/dockerfile:1.5-labs

ARG BASE_IMAGE=registry.fedoraproject.org/fedora:41
FROM --platform=$TARGETPLATFORM ${BASE_IMAGE} AS base

# DO NOT UPDATE THIS BY HAND !!
# Use hack/update-go-container.sh to update the version and hashes.
ARG GO_VERSION=1.24.13
ARG GO_LINUX_ARM64_SHA256=74d97be1cc3a474129590c67ebf748a96e72d9f3a2b6fef3ed3275de591d49b3
ARG GO_LINUX_AMD64_SHA256=1fc94b57134d51669c72173ad5d49fd62afb0f1db9bf3f798fd98ee423f8d730
ARG GO_LINUX_PPC64LE_SHA256=5f0dfab58ce15a84d824363c041246c76847a69d14f9ffac16bd5342299ecc14
ARG GO_LINUX_S390X_SHA256=a3e3e2012f9b4d392fab85fd4596bbd798ea8e0ceba259f47023b8cb5ebfffc1

FROM base AS base-amd64
ADD --checksum=sha256:${GO_LINUX_AMD64_SHA256} https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz .

FROM base AS base-arm64
ADD --checksum=sha256:${GO_LINUX_ARM64_SHA256} https://go.dev/dl/go${GO_VERSION}.linux-arm64.tar.gz .

FROM base AS base-ppc64le
ADD --checksum=sha256:${GO_LINUX_PPC64LE_SHA256} https://go.dev/dl/go${GO_VERSION}.linux-ppc64le.tar.gz .

FROM base AS base-s390x
ADD --checksum=sha256:${GO_LINUX_S390X_SHA256} https://go.dev/dl/go${GO_VERSION}.linux-s390x.tar.gz .

ARG TARGETARCH
FROM base-${TARGETARCH}

ARG TARGETARCH
ARG GO_VERSION
RUN tar -C /usr/local -xzf go${GO_VERSION}.linux-${TARGETARCH}.tar.gz && \
	rm go${GO_VERSION}.linux-${TARGETARCH}.tar.gz

# install cgo-related dependencies
RUN set -eux; \
	dnf install -y \
	g++ \
	gcc \
	glibc-devel \
	make \
	pkg-config \
	; \
	dnf clean all

ENV PATH=/usr/local/go/bin:$PATH

RUN set -eux; go version

ENV GOPATH=/go
ENV PATH=$GOPATH/bin:$PATH
RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 1777 "$GOPATH"
WORKDIR $GOPATH
