# syntax=docker/dockerfile:1.5-labs

ARG BASE_IMAGE=registry.fedoraproject.org/fedora:41
FROM --platform=$TARGETPLATFORM ${BASE_IMAGE} AS base

# DO NOT UPDATE THIS BY HAND !!
# Use hack/update-go-container.sh to update the version and hashes.
ARG GO_VERSION=1.23.6
ARG GO_LINUX_ARM64_SHA256=561c780e8f4a8955d32bf72e46af0b5ee5e0debe1e4633df9a03781878219202
ARG GO_LINUX_AMD64_SHA256=9379441ea310de000f33a4dc767bd966e72ab2826270e038e78b2c53c2e7802d
ARG GO_LINUX_PPC64LE_SHA256=0f817201e83d78ddbfa27f5f78d9b72450b92cc21d5e045145efacd0d3244a99
ARG GO_LINUX_S390X_SHA256=321e7ed0d5416f731479c52fa7610b52b8079a8061967bd48cec6d66f671a60e

FROM base AS base-amd64
ADD --checksum=sha256:${GO_LINUX_AMD64_SHA256} https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz .

FROM base AS base-arm64
ADD --checksum=sha256:${GO_LINUX_ARM64_SHA256} https://go.dev/dl/go${GO_VERSION}.linux-arm64.tar.gz .

FROM base AS base-ppc64le
ADD --checksum=sha256:${GO_LINUX_PPC64LE_SHA256} https://go.dev/dl/go${GO_VERSION}.linux-ppc64le.tar.gz .

FROM base AS base-s390x
ADD --checksum=sha256:${GO_LINUX_S390X_SHA256} https://go.dev/dl/go${GO_VERSION}.linux-s390x.tar.gz .

ARG TARGETARCH
FROM base-${TARGETARCH}

ARG TARGETARCH
ARG GO_VERSION
RUN tar -C /usr/local -xzf go${GO_VERSION}.linux-${TARGETARCH}.tar.gz && \
	rm go${GO_VERSION}.linux-${TARGETARCH}.tar.gz

# install cgo-related dependencies
RUN set -eux; \
	dnf install -y \
	g++ \
	gcc \
	glibc-devel \
	make \
	pkg-config \
	; \
	dnf clean all

ENV PATH=/usr/local/go/bin:$PATH

RUN set -eux; go version

ENV GOPATH=/go
ENV PATH=$GOPATH/bin:$PATH
RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 1777 "$GOPATH"
WORKDIR $GOPATH
