# syntax=docker/dockerfile:1.5-labs

ARG BASE_IMAGE=registry.fedoraproject.org/fedora:41
FROM --platform=$TARGETPLATFORM ${BASE_IMAGE} AS base

# DO NOT UPDATE THIS BY HAND !!
# Use hack/update-go-container.sh to update the version and hashes.
ARG GO_VERSION=1.24.11
ARG GO_LINUX_ARM64_SHA256=beaf0f51cbe0bd71b8289b2b6fa96c0b11cd86aa58672691ef2f1de88eb621de
ARG GO_LINUX_AMD64_SHA256=bceca00afaac856bc48b4cc33db7cd9eb383c81811379faed3bdbc80edb0af65
ARG GO_LINUX_PPC64LE_SHA256=f770d0c5d7e7e2edb030133ac7854d9204f4e954e79a176e81362ffedf6ea34c
ARG GO_LINUX_S390X_SHA256=5955ddda3445b2cbfd81b8772044084911f55d0baeb32414da0411f6a377a2d4

FROM base AS base-amd64
ADD --checksum=sha256:${GO_LINUX_AMD64_SHA256} https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz .

FROM base AS base-arm64
ADD --checksum=sha256:${GO_LINUX_ARM64_SHA256} https://go.dev/dl/go${GO_VERSION}.linux-arm64.tar.gz .

FROM base AS base-ppc64le
ADD --checksum=sha256:${GO_LINUX_PPC64LE_SHA256} https://go.dev/dl/go${GO_VERSION}.linux-ppc64le.tar.gz .

FROM base AS base-s390x
ADD --checksum=sha256:${GO_LINUX_S390X_SHA256} https://go.dev/dl/go${GO_VERSION}.linux-s390x.tar.gz .

ARG TARGETARCH
FROM base-${TARGETARCH}

ARG TARGETARCH
ARG GO_VERSION
RUN tar -C /usr/local -xzf go${GO_VERSION}.linux-${TARGETARCH}.tar.gz && \
	rm go${GO_VERSION}.linux-${TARGETARCH}.tar.gz

# install cgo-related dependencies
RUN set -eux; \
	dnf install -y \
	g++ \
	gcc \
	glibc-devel \
	make \
	pkg-config \
	; \
	dnf clean all

ENV PATH=/usr/local/go/bin:$PATH

RUN set -eux; go version

ENV GOPATH=/go
ENV PATH=$GOPATH/bin:$PATH
RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 1777 "$GOPATH"
WORKDIR $GOPATH
