apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-api-adaptor-deployment
  namespace: confidential-containers-system
  labels:
    app: cloud-api-adaptor
spec:
  template:
    spec:
      containers:
      - name: cloud-api-adaptor-con
        volumeMounts:
        - mountPath: /run/peerpod/cri-runtime.sock # in-container default
          name: cri-runtime-endpoint
      volumes:
      - name: cri-runtime-endpoint
        type: Socket
        hostPath:
          path: /run/containerd/containerd.sock # SET! (crio's default: /var/run/crio/crio.sock)

# to apply this uncomment the patchesStrategicMerge of this file in kustomization.yaml
