# alpine:3.23
FROM --platform="${TARGETPLATFORM}" alpine@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659
RUN addgroup -g 1000 otheruser && \
    adduser -G otheruser -u 1000 -s /bin/bash -D otheruser
USER otheruser
ENTRYPOINT [ "/bin/sh", "-c", "whoami" ]
