#
# (C) Copyright IBM Corp. 2022.
# SPDX-License-Identifier: Apache-2.0
#
---

- hosts: all
  remote_user: root
  environment:
    CLOUD_PROVIDER: ibmcloud
  tasks:
    - name: Set COS service endpoint for IBM Cloud
      set_fact:
        ibmcloud_cos_service_endpoint: https://s3.{{ ibmcloud_region_name }}.cloud-object-storage.appdomain.cloud
      when: ibmcloud_api_endpoint == "https://cloud.ibm.com"
    - name: Set COS service endpoint for IBM Cloud test
      set_fact:
        ibmcloud_cos_service_endpoint: https://s3.us-west.cloud-object-storage.test.appdomain.cloud
      when: ibmcloud_api_endpoint == "https://test.cloud.ibm.com"
    - name: Build peer pod VM image
      shell:
        cmd: |
          . ~/.bashrc
          make build
        chdir: cloud-api-adaptor/ibmcloud/image
    - name: Push peer pod VM image to Cloud Object Store and verify the image
      environment:
        IBMCLOUD_API_KEY: "{{ ibmcloud_api_key }}"
        IBMCLOUD_API_ENDPOINT: "{{ ibmcloud_api_endpoint }}"
        IBMCLOUD_COS_SERVICE_INSTANCE: "{{ ibmcloud_cos_service_instance }}"
        IBMCLOUD_COS_BUCKET: "{{ ibmcloud_cos_bucket }}"
        IBMCLOUD_COS_REGION: "{{ ibmcloud_region_name }}"
        IBMCLOUD_COS_SERVICE_ENDPOINT: "{{ ibmcloud_cos_service_endpoint }}"
        IBMCLOUD_VPC_NAME: "{{ ibmcloud_vpc_name }}"
        IBMCLOUD_VPC_SUBNET_NAME: "{{ ibmcloud_vpc_subnet_name }}"
        IBMCLOUD_VPC_REGION: "{{ ibmcloud_region_name }}"
        IBMCLOUD_VPC_ZONE: "{{ ibmcloud_vpc_zone }}"
      shell:
        cmd: |
          . ~/.bashrc
          make push
          make verify
        chdir: cloud-api-adaptor/ibmcloud/image
