apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloud-api-adaptor-daemonset
  namespace: confidential-containers-system
  labels:
    app: cloud-api-adaptor
spec:
  template:
    spec:
      containers:
      - name: cloud-api-adaptor-con
        volumeMounts:
        - mountPath: /run/cri-runtime # in-container CRI_RUNTIME_ENDPOINT default
          name: cri-runtime-endpoint
      volumes:
      - name: cri-runtime-endpoint
        hostPath:
          path: /run/containerd # SET! (crio's default: /var/run/crio/crio.sock)
          type: Directory

# to apply this uncomment the patchesStrategicMerge of this file in kustomization.yaml
