#
# (C) Copyright IBM Corp. 2022.
# SPDX-License-Identifier: Apache-2.0
#
---

- hosts: all
  remote_user: root
  tasks:
    - name: Set IBM Cloud Endpoints
      set_fact:
        ibmcloud_iam_endpoint: https://iam.cloud.ibm.com/identity/token
        ibmcloud_vpc_endpoint: "https://{{ ibmcloud_vpc_region_name }}.iaas.cloud.ibm.com/v1"
      when: ibmcloud_api_endpoint == "https://cloud.ibm.com"
    - name: Set Test IBM Cloud Endpoints
      set_fact:
        ibmcloud_iam_endpoint: https://iam.test.cloud.ibm.com/identity/token
        ibmcloud_vpc_endpoint: https://us-south-stage01.iaasdev.cloud.ibm.com/v1
      when: ibmcloud_api_endpoint == "https://test.cloud.ibm.com"
    - name: Start the Cloud API Adaptor
      async: 10
      poll: 0
      shell:
        cmd: |  
          /usr/local/bin/cloud-api-adaptor ibmcloud \
              -api-key "{{ ibmcloud_api_key }}" \
              -iam-service-url "{{ ibmcloud_iam_endpoint }}" \
              -vpc-service-url "{{ ibmcloud_vpc_endpoint }}" \
              -resource-group-id "{{ ibmcloud_resource_group_id }}" \
              -key-id "{{ ibmcloud_vpc_ssh_key_id }}" \
              -image-id "{{ ibmcloud_vpc_podvm_image_id }}" \
              -profile-name "{{ ibmcloud_vpc_podvm_instance_profile_name }}" \
              -zone-name "{{ ibmcloud_vpc_zone_name }}" \
              -primary-subnet-id "{{ ibmcloud_vpc_subnet_id }}" \
              -primary-security-group-id "{{ ibmcloud_vpc_security_group_id }}" \
              -vpc-id "{{ ibmcloud_vpc_id }}" \
              -pods-dir /run/peerpod/pods \
              -cri-runtime-endpoint "{{ ibmcloud_cri_runtime_endpoint }}" \
              -socket /run/peerpod/hypervisor.sock \
              > /var/log/cloud-api-adaptor.log 2>&1 &