server_addr = "unix:///run/kata-containers/agent.sock"

# This field sets up the KBC that attestation agent uses
# This is replaced in the makefile steps so do not set it manually
aa_kbc_params = ""

# This field sets up the container registry auth
image_registry_auth_file = "file:///etc/attestation-agent/auth.json"

# Do not spawn guest components in kata agent
guest_components_procs = "none"
