# Adapted from https://github.com/kubernetes-sigs/kind/blob/main/images/base/Dockerfile

ARG BASE_IMAGE=ubuntu:24.04

FROM $BASE_IMAGE AS iptables

ARG DEBIAN_FRONTEND=noninteractive

COPY ./versions.yaml /versions.yaml

RUN echo "Building iptables-wrapper... " \
    && apt-get update \
    && apt-get install -y git golang build-essential \
    && git clone https://github.com/kubernetes-sigs/iptables-wrappers.git /iptables \
    && cd /iptables \
    && version=$(grep 'iptables-wrapper:' /versions.yaml | awk '{print $2}') \
    && git checkout $version \
    && make BIN_DIR=. build \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

FROM $BASE_IMAGE AS base

ARG DEBIAN_FRONTEND=noninteractive

RUN echo "Installing Packages ..." \
    && apt-get update \
    && apt-get install -y \
    systemd \
    conntrack iptables nftables iproute2 ethtool util-linux kmod \
    libseccomp2 pigz fuse-overlayfs \
    nfs-common systemd-sysv \
    bash ca-certificates curl jq procps \
    && rm -f /lib/systemd/system/multi-user.target.wants/* \
    && rm -f /etc/systemd/system/*.wants/* \
    && rm -f /lib/systemd/system/local-fs.target.wants/* \
    && rm -f /lib/systemd/system/sockets.target.wants/*udev* \
    && rm -f /lib/systemd/system/sockets.target.wants/*initctl* \
    && rm -f /lib/systemd/system/basic.target.wants/* \
    && echo "ReadKMsg=no" >> /etc/systemd/journald.conf \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN echo "Enabling / Disabling services ... " \
    && systemctl mask systemd-binfmt.service \
    && systemctl enable systemd-logind dbus.socket

RUN --mount=type=cache,target=/iptables,from=iptables,source=/iptables,readonly \
    cp /iptables/iptables-wrapper /usr/sbin \
    && /usr/sbin/iptables-wrapper install

# Add podvm resources
COPY ./podvm/resources/binaries-tree/etc/ /etc/
COPY ./podvm/resources/binaries-tree/usr/ /usr/
COPY ./podvm/resources/binaries-tree/pause_bundle/ /pause_bundle/

COPY ./podvm/misc-settings.sh /tmp/misc-settings.sh

RUN CLOUD_PROVIDER=generic bash /tmp/misc-settings.sh

COPY --chmod=0755 ./podvm/entrypoint.sh  /usr/local/bin/

# https://systemd.io/CONTAINER_INTERFACE/
ENV container=docker

# systemd exits on SIGRTMIN+3, not SIGTERM (which re-executes it)
# https://bugzilla.redhat.com/show_bug.cgi?id=1201657
STOPSIGNAL SIGRTMIN+3
ENTRYPOINT [ "/usr/local/bin/entrypoint.sh", "/sbin/init" ]
