# syntax=docker/dockerfile:1.5.0-labs
# ubuntu:24.04
FROM ubuntu@sha256:0d39fcc8335d6d74d5502f6df2d30119ff4790ebbb60b364818d5112d9e3e932 AS builder

ARG MKOSI_VERSION="v26"
ARG PROFILE="debug"
ARG IMAGE_VERSION="0.0.0"

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
	apt-get install -y \
	binutils \
	bubblewrap \
	git \
	cpio \
	systemd-repart \
	kmod \
	systemd-boot-efi \
	libcryptsetup12 \
	squashfs-tools \
	systemd-ukify \
	dosfstools \
	mtools \
	python3 \
	debian-archive-keyring \
	zstd

RUN mkdir -p /build
WORKDIR /build
RUN git clone -b "$MKOSI_VERSION" https://github.com/systemd/mkosi
ENV PATH="/build/mkosi/bin:$PATH"
RUN mkosi --version

RUN mkdir /image
WORKDIR /image
COPY mkosi.images /image/mkosi.images
COPY mkosi.skeleton-debug /image/mkosi.skeleton-debug
COPY mkosi.skeleton-sftp /image/mkosi.skeleton-sftp
COPY mkosi.workspace /image/mkosi.workspace
COPY resources /image/resources
COPY mkosi.conf /image/mkosi.conf
RUN --security=insecure mkosi --profile=$PROFILE --image-version=$IMAGE_VERSION

RUN mkdir -p /msmt
RUN for section in linux initrd cmdline osrel uname sbat; do \
		objcopy --dump-section .$section=/msmt/$section /image/build/system.efi; \
	done
RUN /usr/lib/systemd/systemd-measure calculate \
		--linux=/msmt/linux \
		--osrel=/msmt/osrel \
		--cmdline=/msmt/cmdline \
		--initrd=/msmt/initrd \
		--uname=/msmt/uname \
		--sbat=/msmt/sbat \
		--phase=: \
		--bank=sha256 \
		--json=short > /image/build/system.measurement.json

FROM scratch

COPY --from=builder /image/build/system.raw /
COPY --from=builder /image/build/system.measurement.json /
