# Adapted from https://github.com/kubernetes-sigs/kind/blob/main/images/base/Dockerfile

ARG BASE_IMAGE=registry.fedoraproject.org/fedora:42

FROM $BASE_IMAGE AS iptables

RUN echo "Building iptables-wrapper... " \
    && dnf install -y git golang \
    && git clone https://github.com/kubernetes-sigs/iptables-wrappers.git /iptables \
    && cd /iptables \
    && make BIN_DIR=. build

FROM $BASE_IMAGE AS base

RUN echo "Installing Packages ..." \
    && dnf install -y \
      systemd \
      conntrack iptables iptables-legacy iptables-nft nftables iproute ethtool util-linux kmod \
      libseccomp pigz fuse-overlayfs \
      nfs-utils which systemd-pam \
      bash ca-certificates curl jq procps \
    && rm -f /lib/systemd/system/multi-user.target.wants/* \
    && rm -f /etc/systemd/system/*.wants/* \
    && rm -f /lib/systemd/system/local-fs.target.wants/* \
    && rm -f /lib/systemd/system/sockets.target.wants/*udev* \
    && rm -f /lib/systemd/system/sockets.target.wants/*initctl* \
    && rm -f /lib/systemd/system/basic.target.wants/* \
    && echo "ReadKMsg=no" >> /etc/systemd/journald.conf

RUN echo "Enabling / Disabling services ... " \
    && systemctl mask systemd-binfmt.service \
    && systemctl enable systemd-logind dbus.socket

RUN --mount=type=cache,target=/iptables,from=iptables,source=/iptables,readonly \
    cd /iptables && ./iptables-wrapper-installer.sh --no-sanity-check --no-cleanup

# Add podvm resources
COPY ./resources/binaries-tree/etc/ /etc/
COPY ./resources/binaries-tree/usr/ /usr/
COPY ./resources/binaries-tree/pause_bundle/ /pause_bundle/

RUN curl -LO https://raw.githubusercontent.com/confidential-containers/cloud-api-adaptor/main/src/cloud-api-adaptor/podvm/qcow2/misc-settings.sh

RUN PODVM_DISTRO=ubuntu CLOUD_PROVIDER=generic bash ./misc-settings.sh

COPY --chmod=0755 entrypoint.sh  /usr/local/bin/

# https://systemd.io/CONTAINER_INTERFACE/
ENV container=docker

# systemd exits on SIGRTMIN+3, not SIGTERM (which re-executes it)
# https://bugzilla.redhat.com/show_bug.cgi?id=1201657
STOPSIGNAL SIGRTMIN+3
ENTRYPOINT [ "/usr/local/bin/entrypoint.sh", "/sbin/init" ]
