apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: bitnami/nginx
    name: nginx
    resources: 
      requests:
        cpu: 1
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi
  runtimeClassName: kata-remote-cc
