apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azuredisk
spec:
  storageClassName: azure-disk-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
