apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: cloud-api-adaptor
  name: cloud-api-adaptor-daemonset
  namespace: confidential-containers-system
spec:
  selector:
    matchLabels:
      app: cloud-api-adaptor
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: cloud-api-adaptor
    spec:
      serviceAccountName: cloud-api-adaptor
      containers:
      - command:
        - /usr/local/bin/entrypoint.sh
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        envFrom:
        - secretRef:
            name: peer-pods-secret
        - configMapRef:
            name: peer-pods-cm
        image: cloud-api-adaptor
        imagePullPolicy: Always
        name: cloud-api-adaptor-con
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_ADMIN
        startupProbe:
          httpGet:
            path: /startup
            port: 8000
          failureThreshold: 30
          periodSeconds: 20
          initialDelaySeconds: 20
        volumeMounts:
        - name: auth-json
          mountPath: "/root/containers/" # hardcoded
          readOnly: true
        - mountPath: /root/.ssh/
          name: ssh
          readOnly: true
        - mountPath: /run/peerpod
          name: pods-dir
        - mountPath: /run/netns
          mountPropagation: HostToContainer
          name: netns
      hostNetwork: true
      nodeSelector:
        node.kubernetes.io/worker: ""
      volumes:
      - name: auth-json
        secret:
          secretName: auth-json-secret
          optional: true # failing?
      - name: ssh
        secret:
          defaultMode: 384
          optional: true
          secretName: ssh-key-secret
      - hostPath:
          path: /run/peerpod
        name: pods-dir
      - hostPath:
          path: /run/netns
        name: netns
