apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloud-api-adaptor-daemonset
  namespace: confidential-containers-system
  labels:
    app: cloud-api-adaptor
spec:
  selector:
    matchLabels:
      app: cloud-api-adaptor
  template:
    metadata:
      labels:
        app: cloud-api-adaptor
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      hostNetwork: true
      containers:
      - name: cloud-api-adaptor-con
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_ADMIN"]
        image: kustomize.this/cloud-api-adaptor/image:url
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: peer-pods-secret
        - configMapRef:
            name: peer-pods-cm
        command: ["/usr/local/bin/entrypoint.sh"]
        volumeMounts:
        - name: ssh
          mountPath: "/root/.ssh/"
          readOnly: true
        - mountPath: /run/peerpod
          name: pods-dir
        - mountPath: /run/netns
          mountPropagation: HostToContainer
          name: netns
      volumes:
      - name: ssh
        secret:
          secretName: ssh-key-secret
          defaultMode: 0600
          optional: true
      - name: pods-dir # drop?
        hostPath:
          path: /run/peerpod
      - name: netns
        #readOnly: true
        hostPath:
          path: /run/netns
---
apiVersion: confidentialcontainers.org/v1beta1
kind: CcRuntime
metadata:
  name: ccruntime-sample
  namespace: confidential-containers-system
spec:
  # Add fields here
  runtimeName: kata
  ccNodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker: ""
  config:
    installType: bundle
    payloadImage: quay.io/confidential-containers/peer-pods-runtime-payload:2022091512521663246365
    installDoneLabel:
      katacontainers.io/kata-runtime: "true"
    uninstallDoneLabel:
      katacontainers.io/kata-runtime: "cleanup"
    installerVolumeMounts:
      - mountPath: /etc/crio/
        name: crio-conf
      - mountPath: /etc/containerd/
        name: containerd-conf
      - mountPath: /opt/confidential-containers/
        name: kata-artifacts
      - mountPath: /var/run/dbus
        name: dbus
      - mountPath: /run/systemd
        name: systemd
      - mountPath: /usr/local/bin/
        name: local-bin
    installerVolumes:
      - hostPath:
          path: /etc/crio/
          type: ""
        name: crio-conf
      - hostPath:
          path: /etc/containerd/
          type: ""
        name: containerd-conf
      - hostPath:
          path: /opt/confidential-containers/
          type: DirectoryOrCreate
        name: kata-artifacts
      - hostPath:
          path: /var/run/dbus
          type: ""
        name: dbus
      - hostPath:
          path: /run/systemd
          type: ""
        name: systemd
      - hostPath:
          path: /usr/local/bin/
          type: ""
        name: local-bin
    installCmd: ["/opt/kata-artifacts/scripts/kata-deploy.sh", "install"]
    uninstallCmd: ["/opt/kata-artifacts/scripts/kata-deploy.sh", "cleanup"]
    cleanupCmd: ["/opt/kata-artifacts/scripts/kata-deploy.sh", "reset"]
    environmentVariables:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: spec.nodeName
      - name: "CONFIGURE_CC"
        value: "yes"
