name: azure nightly build

on:
  schedule:
    # Run at 12:00 AM UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-image-version:
    runs-on: ubuntu-latest
    outputs:
      image-version: "${{ steps.generate-image-version.outputs.image-version }}"
    steps:
    - name: Generate version for pod vm image
      id: generate-image-version
      run: |
        nightly_version=$(date +'%Y.%m.%d')
        echo "Generated nightly version for the image as: ${nightly_version}"
        echo "image-version=${nightly_version}" >> "$GITHUB_OUTPUT"

  build-podvm-image:
    needs:
    - generate-image-version
    uses: ./.github/workflows/azure-podvm-image-build.yml
    secrets: inherit
    with:
      image-version: ${{ needs.generate-image-version.outputs.image-version }}

  e2e-test:
    needs:
    - build-podvm-image
    uses: ./.github/workflows/azure-e2e-test.yml
    secrets: inherit
    with:
      podvm-image-id: ${{ needs.build-podvm-image.outputs.image-id }}
