name: azure podvm image nightly build

on:
  schedule:
    # Run at 12:00 AM UTC
    - cron: '0 0 * * *'

jobs:
  generate-image-version:
    runs-on: ubuntu-latest
    outputs:
      image-version: "${{ steps.generate-image-version.outputs.image-version }}"
    steps:
    - name: Generate version for pod vm image
      id: generate-image-version
      run: |
        nightly_version=$(date +'%Y.%m.%d')
        echo "Generated nightly version for the image as: ${nightly_version}"
        echo "image-version=${nightly_version}" >> "$GITHUB_OUTPUT"

  build-podvm-image:
    needs:
    - generate-image-version
    uses: confidential-containers/cloud-api-adaptor/.github/workflows/azure-podvm-image-build.yml@main
    secrets: inherit
    with:
      image-version: ${{ needs.generate-image-version.outputs.image-version }}
