# (C) Copyright Confidential Containers Contributors
# # SPDX-License-Identifier: Apache-2.0
#
# Build binary with all providers.
---
name: build-all
on: [pull_request]
jobs:
  build_job:
    name: build-all
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        type:
          - dev
          - release
        runner:
          - ubuntu-latest
        go_version:
          - 1.18

    steps:
      - name: Checkout the pull request code
        uses: actions/checkout@v3
      - name: Setup Golang version ${{ matrix.go_version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}
      - name: Install build dependencies
        if: matrix.type == 'dev'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libvirt-dev
      - name: Build
        run: |
          # Build the binaries 
          if [ ${{ matrix.type }} == "release" ]; then
            RELEASE_BUILD=true make build
          else
            RELEASE_BUILD=false make build
          fi
