# (C) Copyright Confidential Containers Contributors 2023.
# SPDX-License-Identifier: Apache-2.0
#
# Build and push container images for each cloud provider.
---
name: daily e2e test for ibmcloud (amd64)
on:
  schedule:
    # Runs "at 05:00(UTC time) every day" (see https://crontab.guru)
    # will base on default branch `staging`
    - cron: '0 5 * * *'
  push:
    branches:    
      - daily-e2e-ibmcloud
      - develop
env:
  go_version: 1.19

jobs:
  daily-e2e-amd64:
    name: daily e2e test for ibmcloud with operator
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Setup Golang version ${{ matrix.go_version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl
          sudo curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          echo "Install IBM Cloud CLI"
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          echo "Install COS Plugin"
          ibmcloud plugin install cloud-object-storage -f
      - name: Config IBM E2E COS
        run: |
          ibmcloud cos config crn --crn $crn --force | grep -v ^FAILED$ || exit 1
          ibmcloud cos config auth --method HMAC | grep -v ^FAILED$ || exit 1
          echo -e $access_key_id "\n" $secret_access_key | ibmcloud cos config hmac
          ibmcloud cos config endpoint-url --url $endpoint | grep -v ^FAILED$ || exit 1
          ibmcloud cos config list
        env:
          crn: ${{ secrets.IBM_E2E_COS_CRN }}
          endpoint: "https://s3.jp-tok.cloud-object-storage.appdomain.cloud"
          access_key_id: ${{ secrets.IBM_E2E_COS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.IBM_E2E_COS_SECRET_ACCESS_KEY }}
      - name: Check ibmcloud e2e test result
        run: |
          date_name=$(date +"%y%m%d")
          echo $date_name
          log_name=$(ibmcloud cos objects --bucket $bucket_name |grep $date_name |grep amd64 | awk 'END { print $1 }')
          echo $log_name
          ibmcloud cos object-get --bucket daily-e2e-test-bucket --key=$log_name $log_name
          cat $log_name
          last_line=$(awk 'END {print}' $log_name)
          if [[ $last_line = "Finished: SUCCESS" ]]; then
            echo "ibmcloud e2e test(amd64) is passed."
          else
            echo "ibmcloud e2e test(amd64) is failed."
            exit 2
          fi
        env:
          bucket_name : "daily-e2e-test-bucket"
