# (C) Copyright Confidential Containers Contributors 2023.
# SPDX-License-Identifier: Apache-2.0
#
# Run end-to-end (e2e) tests.
---
name: (Callable) Run all e2e tests

on:
  workflow_call:
    inputs:
      caa_image_tag:
        description: set the cloud-api-adaptor image tag
        required: true
        type: string
      git_ref:
        default: 'main'
        description: Git ref to checkout the cloud-api-adaptor repository. Defaults to main.
        required: false
        type: string
      podvm_image_tag:
        description: set the podvm image tag
        required: true
        type: string
      registry:
        description: the container registry where built images will be pushed to
        required: true
        type: string
    secrets:
      AWS_IAM_ROLE_ARN:
        required: true
      QUAY_PASSWORD:
        required: true
      REGISTRY_CREDENTIAL_ENCODED:
        required: true

env:
  # cloud-api-adaptor image registry
  E2E_IMG_REGISTRY: ${{ inputs.registry }}
  # cloud-api-adaptor: image release tag
  E2E_IMG_RELEASE_TAG: ${{ inputs.caa_image_tag }}
  # cloud-api-adaptor image dev tag
  E2E_IMG_DEV_TAG: ${{ inputs.caa_image_tag }}-dev

defaults:
  run:
    working-directory: src/cloud-api-adaptor

permissions: {}

jobs:
  podvm_mkosi_amd64:
    uses: ./.github/workflows/podvm_mkosi.yaml
    with:
      registry: ${{ inputs.registry }}
      image_tag: ${{ inputs.podvm_image_tag }}
      git_ref: ${{ inputs.git_ref }}
      arch: amd64
      debug: true
    permissions:
      contents: read  # Required to checkout code
      packages: write  # Required to push container images
      id-token: write  # Required for OIDC authentication
      attestations: write  # Required to write attestations
      artifact-metadata: write  # Required by podvm_mkosi.yaml to write attestation metadata
    secrets:
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

  podvm_mkosi_s390x:
    uses: ./.github/workflows/podvm_mkosi.yaml
    with:
      registry: ${{ inputs.registry }}
      image_tag: ${{ inputs.podvm_image_tag }}
      git_ref: ${{ inputs.git_ref }}
      arch: s390x
      debug: true
    permissions:
      contents: read  # Required to checkout code
      packages: write  # Required to push container images
      attestations: write  # Required to write attestations
      id-token: write  # Required for OIDC authentication
      artifact-metadata: write  # Required by podvm_mkosi.yaml to write attestation metadata
    secrets:
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

  podvm_ubuntu_amd64:
    uses: ./.github/workflows/podvm_mkosi_ubuntu.yaml
    with:
      registry: ${{ inputs.registry }}
      image_tag: ${{ inputs.podvm_image_tag }}
      git_ref: ${{ inputs.git_ref }}
      arch: amd64
      debug: true
    permissions:
      contents: read # Required if we want to run on a fork?
      packages: write # Required to publish the oras package to ghcr
      id-token: write # Required to publish the attestation provenance to ghcr
      attestations: write # Required to publish the attestation provenance to ghcr
      artifact-metadata: write # Required by podvm_mkosi_ubuntu.yaml to write attestation metadata
    secrets:
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

  podvm_ubuntu_s390x:
    uses: ./.github/workflows/podvm_mkosi_ubuntu.yaml
    with:
      registry: ${{ inputs.registry }}
      image_tag: ${{ inputs.podvm_image_tag }}
      git_ref: ${{ inputs.git_ref }}
      arch: s390x
      debug: true
    permissions:
      contents: read # Required if we want to run on a fork?
      packages: write # Required to publish the oras package to ghcr
      id-token: write # Required to publish the attestation provenance to ghcr
      attestations: write # Required to publish the attestation provenance to ghcr
      artifact-metadata: write # Required by podvm_mkosi_ubuntu.yaml to write attestation metadata
    secrets:
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

  caa_image_amd64:
    uses: ./.github/workflows/caa_build_and_push.yaml
    with:
      registry: ${{ inputs.registry }}
      dev_arches: 'linux/amd64'
      release_arches: 'linux/amd64'
      dev_tags: ${{ inputs.caa_image_tag }}-dev
      release_tags: ${{ inputs.caa_image_tag }}
      git_ref: ${{ inputs.git_ref }}
    permissions:
      contents: read  # Required to checkout code
      packages: write  # Required to push container images
    secrets:
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

  caa_image_s390x:
    uses: ./.github/workflows/caa_build_and_push.yaml
    with:
      registry: ${{ inputs.registry }}
      dev_arches: 'linux/s390x'
      release_arches: 'linux/s390x'
      dev_tags: ${{ inputs.caa_image_tag }}-dev
      release_tags: ${{ inputs.caa_image_tag }}
      git_ref: ${{ inputs.git_ref }}
      runner: 'ubuntu-24.04-s390x'
    permissions:
      contents: read  # Required to checkout code
      packages: write  # Required to push container images
    secrets:
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

  # Build and push the peerpod-ctrl image (per-arch)
  peerpod_ctrl_image_amd64:
    uses: ./.github/workflows/peerpod-ctrl_build_and_push.yaml
    with:
      registry: ${{ inputs.registry }}
      image_tags: ${{ inputs.caa_image_tag }}
      git_ref: ${{ inputs.git_ref }}
      arch: linux/amd64
      runner: ubuntu-24.04
    permissions:
      contents: read
      packages: write # Required to publish the image to ghcr
    secrets:
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

  peerpod_ctrl_image_s390x:
    uses: ./.github/workflows/peerpod-ctrl_build_and_push.yaml
    with:
      registry: ${{ inputs.registry }}
      image_tags: ${{ inputs.caa_image_tag }}
      git_ref: ${{ inputs.git_ref }}
      arch: linux/s390x
      runner: ubuntu-24.04-s390x
    permissions:
      contents: read
      packages: write # Required to publish the image to ghcr
    secrets:
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

  # Build and push the webhook image
  webhook_image:
    uses: ./.github/workflows/webhook_image.yaml
    with:
      registry: ${{ inputs.registry }}
      image_tags: ${{ inputs.caa_image_tag }}
      git_ref: ${{ inputs.git_ref }}
    permissions:
      contents: read
      packages: write # Required to publish the image to ghcr
    secrets:
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

  # Run AWS e2e tests if pull request labeled 'test_e2e_aws'
  aws:
    name: aws
    if: |
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.pull_request.labels.*.name, 'test_e2e_aws')
    needs: [podvm_ubuntu_amd64, caa_image_amd64, peerpod_ctrl_image_amd64, webhook_image]
    strategy:
      fail-fast: false
      matrix:
        container_runtime:
          - crio
    permissions:
      id-token: write # Required by aws-actions/configure-aws-credentials
      contents: read  # Required by aws-actions/configure-aws-credentials
    uses: ./.github/workflows/e2e_aws.yaml
    with:
      caa_image: ${{ inputs.registry }}/cloud-api-adaptor:${{ inputs.caa_image_tag }}-dev-amd64
      container_runtime: ${{ matrix.container_runtime }}
      podvm_image: ${{ needs.podvm_ubuntu_amd64.outputs.qcow2_oras_image }}
      git_ref: ${{ inputs.git_ref }}
      peerpod_ctrl_image: ${{ inputs.registry }}/peerpod-ctrl:${{ inputs.caa_image_tag }}-amd64
      webhook_image: ${{ inputs.registry }}/peer-pods-webhook:${{ inputs.caa_image_tag }}
    secrets:
      AWS_IAM_ROLE_ARN: ${{ secrets.AWS_IAM_ROLE_ARN }}

  libvirt_e2e_arch_prep:
    name: libvirt_e2e_arch_prep
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ inputs.git_ref }}

      - name: Rebase the code
        if: github.event_name == 'pull_request_target'
        working-directory: ./
        run: |
          ./hack/ci-helper.sh rebase-atop-of-the-latest-target-branch

  # Run libvirt amd64 e2e tests, based on the mkosi image, if pull request labeled 'test_e2e_libvirt'
  libvirt_amd64:
    name: E2E tests on libvirt for the amd64 architecture
    if: |
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.pull_request.labels.*.name, 'test_e2e_libvirt') ||
      contains(github.event.pull_request.labels.*.name, 'test_e2e_libvirt_amd64')
    needs: [podvm_mkosi_amd64, libvirt_e2e_arch_prep, caa_image_amd64, peerpod_ctrl_image_amd64, webhook_image]
    uses: ./.github/workflows/e2e_libvirt.yaml
    with:
      runner: ubuntu-24.04
      caa_image: ${{ inputs.registry }}/cloud-api-adaptor:${{ inputs.caa_image_tag }}-dev-amd64
      podvm_image: ${{ needs.podvm_mkosi_amd64.outputs.qcow2_oras_image }}
      git_ref: ${{ inputs.git_ref }}
      peerpod_ctrl_image: ${{ inputs.registry }}/peerpod-ctrl:${{ inputs.caa_image_tag }}-amd64
      webhook_image: ${{ inputs.registry }}/peer-pods-webhook:${{ inputs.caa_image_tag }}
    secrets:
      REGISTRY_CREDENTIAL_ENCODED: ${{ secrets.REGISTRY_CREDENTIAL_ENCODED }}

  # Run libvirt s390x e2e tests, based on the mkosi image, if pull request labeled 'test_e2e_libvirt'
  libvirt_s390x:
    name: E2E tests on libvirt for the s390x architecture
    if: |
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.pull_request.labels.*.name, 'test_e2e_libvirt') ||
      contains(github.event.pull_request.labels.*.name, 'test_e2e_libvirt_s390x')
    needs: [podvm_mkosi_s390x, libvirt_e2e_arch_prep, caa_image_s390x, peerpod_ctrl_image_s390x, webhook_image]
    uses: ./.github/workflows/e2e_libvirt.yaml
    with:
      runner: s390x-large
      caa_image: ${{ inputs.registry }}/cloud-api-adaptor:${{ inputs.caa_image_tag }}-dev-s390x
      podvm_image: ${{ needs.podvm_mkosi_s390x.outputs.qcow2_oras_image }}
      git_ref: ${{ inputs.git_ref }}
      peerpod_ctrl_image: ${{ inputs.registry }}/peerpod-ctrl:${{ inputs.caa_image_tag }}-s390x
      webhook_image: ${{ inputs.registry }}/peer-pods-webhook:${{ inputs.caa_image_tag }}
    secrets:
      REGISTRY_CREDENTIAL_ENCODED: ${{ secrets.REGISTRY_CREDENTIAL_ENCODED }}

  # Run libvirt amd64 e2e tests, based on the mkosi image, if pull request labeled 'test_e2e_libvirt'
  libvirt_ubuntu_amd64:
    name: E2E tests on libvirt, with the mkosi_ubuntu podvm image for the amd64 architecture
    if: |
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.pull_request.labels.*.name, 'test_e2e_libvirt') ||
      contains(github.event.pull_request.labels.*.name, 'test_e2e_libvirt_amd64')
    needs: [podvm_ubuntu_amd64, libvirt_e2e_arch_prep, caa_image_amd64, peerpod_ctrl_image_amd64, webhook_image]
    uses: ./.github/workflows/e2e_libvirt.yaml
    with:
      runner: ubuntu-24.04
      caa_image: ${{ inputs.registry }}/cloud-api-adaptor:${{ inputs.caa_image_tag }}-amd64-dev
      podvm_image: ${{ needs.podvm_ubuntu_amd64.outputs.qcow2_oras_image }}
      git_ref: ${{ inputs.git_ref }}
      peerpod_ctrl_image: ${{ inputs.registry }}/peerpod-ctrl:${{ inputs.caa_image_tag }}-amd64
      webhook_image: ${{ inputs.registry }}/peer-pods-webhook:${{ inputs.caa_image_tag }}
    secrets:
      REGISTRY_CREDENTIAL_ENCODED: ${{ secrets.REGISTRY_CREDENTIAL_ENCODED }}

  # Run libvirt s390x e2e tests, based on the mkosi image, if pull request labeled 'test_e2e_libvirt'
  libvirt_ubuntu_s390x:
    name: E2E tests on libvirt, with the mkosi_ubuntu podvm image for the s390x architecture
    if: |
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.pull_request.labels.*.name, 'test_e2e_libvirt') ||
      contains(github.event.pull_request.labels.*.name, 'test_e2e_libvirt_s390x')
    needs: [podvm_ubuntu_s390x, libvirt_e2e_arch_prep, caa_image_s390x, peerpod_ctrl_image_s390x, webhook_image]
    uses: ./.github/workflows/e2e_libvirt.yaml
    with:
      runner: s390x-large
      caa_image: ${{ inputs.registry }}/cloud-api-adaptor:${{ inputs.caa_image_tag }}-s390x-dev
      podvm_image: ${{ needs.podvm_ubuntu_s390x.outputs.qcow2_oras_image }}
      git_ref: ${{ inputs.git_ref }}
      peerpod_ctrl_image: ${{ inputs.registry }}/peerpod-ctrl:${{ inputs.caa_image_tag }}-s390x
      webhook_image: ${{ inputs.registry }}/peer-pods-webhook:${{ inputs.caa_image_tag }}
    secrets:
      REGISTRY_CREDENTIAL_ENCODED: ${{ secrets.REGISTRY_CREDENTIAL_ENCODED }}

  # Run BYOM e2e tests if pull request labeled 'test_e2e_byom'
  byom:
    name: byom
    if: |
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.pull_request.labels.*.name, 'test_e2e_byom')
    needs: [caa_image_amd64, peerpod_ctrl_image_amd64, webhook_image]
    uses: ./.github/workflows/e2e_byom.yaml
    with:
      caa_image: ${{ inputs.registry }}/cloud-api-adaptor:${{ inputs.caa_image_tag }}-dev-amd64
      git_ref: ${{ inputs.git_ref }}
      peerpod_ctrl_image: ${{ inputs.registry }}/peerpod-ctrl:${{ inputs.caa_image_tag }}-amd64
      webhook_image: ${{ inputs.registry }}/peer-pods-webhook:${{ inputs.caa_image_tag }}
