# Copyright Confidential Containers Contributors
# SPDX-License-Identifier: Apache-2.0
#
# Build and push peerpod-ctrl multi-arch manifest image for all arch combinations
---
name: (Callable) Build and push peerpod-ctrl multi-arch manifest image for all arch combinations

on:
  workflow_call:
    inputs:
      registry:
        default: 'quay.io/confidential-containers'
        description: 'Image registry (e.g. "ghcr.io/confidential-containers") where the built image will be pushed to'
        required: false
        type: string
      image_tags:
        description: 'Comma-separated list of tags for the built image (e.g. latest,v1.0.0)'
        required: true
        type: string
      git_ref:
        default: 'main'
        description: Git ref to checkout the cloud-api-adaptor repository. Defaults to main.
        required: false
        type: string
    secrets:
      QUAY_PASSWORD:
        required: true

permissions: {}

jobs:
  build_push_job:
    name: build and push single arch image
    strategy:
      fail-fast: false
      matrix:
        types: [
          { arch: linux/amd64,   runner: ubuntu-24.04 },
          { arch: linux/arm64,   runner: ubuntu-24.04-arm },
          { arch: linux/ppc64le, runner: ubuntu-24.04-ppc64le },
          { arch: linux/s390x,   runner: ubuntu-24.04-s390x },
        ]
    uses: ./.github/workflows/peerpod-ctrl_build_and_push.yaml
    with:
      arch: ${{ matrix.types.arch }}
      image_tags: ${{ inputs.image_tags }}
      git_ref: ${{ inputs.git_ref }}
      registry: ${{ inputs.registry }}
      runner: ${{ matrix.types.runner }}
    secrets:
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
    permissions:
      packages: write  # Required for pushing to GitHub Container Registry

  manifest_job:
    name: generate peerpod-ctrl multi-arch manifest
    runs-on: ubuntu-24.04
    needs: [build_push_job]
    permissions:
      packages: write  # Required for pushing to GitHub Container Registry
    steps:
      - name: Checkout the code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          ref: "${{ inputs.git_ref }}"
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Login to Quay Container Registry
        if: ${{ startsWith(inputs.registry, 'quay.io') }}
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ vars.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Login to Github Container Registry
        if: ${{ startsWith(inputs.registry, 'ghcr.io') }}
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish multi-arch manifest
        working-directory: src/cloud-api-adaptor
        run: |
          ./hack/publish.sh publish-multiarch-manifest
        env:
          IMAGE_REGISTRY: ${{ inputs.registry }}
          IMAGE_NAME: "peerpod-ctrl"
          IMAGE_TAGS: ${{ inputs.image_tags }}
          ARCHES: "amd64,arm64,ppc64le,s390x"
