name: Create a Pod VM image with mkosi

on:
  workflow_dispatch:
    inputs:
      registry:
        default: 'quay.io/confidential-containers'
        required: false
        type: string
      image_tag:
        default: ''
        required: false
        type: string
      git_ref:
        description: Git ref to checkout the cloud-api-adaptor repository.
        required: true
        type: string
      arch:
        description: Which arch we are building the mkosi image for
        default: 'amd64'
        required: false
        type: string
      debug:
        description: Whether to build the image in debug mode
        default: false
        required: false
        type: boolean

  workflow_call:
    inputs:
      registry:
        default: 'quay.io/confidential-containers'
        required: false
        type: string
      image_tag:
        default: ''
        required: false
        type: string
      git_ref:
        description: Git ref to checkout the cloud-api-adaptor repository.
        required: true
        type: string
      arch:
        description: Which arch we are building the mkosi image for
        default: 'amd64'
        required: false
        type: string
      debug:
        description: Whether to build the image in debug mode
        default: false
        required: false
        type: boolean
    secrets:
      QUAY_PASSWORD:
        required: true
    outputs:
      qcow2_oras_image:
        description: The location of the qcow2 oras container this workflow pushed
        value: ${{ jobs.build-image.outputs.qcow2_oras_image }}

defaults:
  run:
    working-directory: src/cloud-api-adaptor

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-mkosi-${{ toJSON(inputs) }}
  cancel-in-progress: true

permissions: {}

jobs:
  build-image:
    name: Build mkosi image for ${{ inputs.arch }}
    runs-on: ${{ inputs.arch == 's390x' && 's390x' || inputs.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    permissions:
      contents: read  # Required for checkout on forks
      packages: write  # Required to publish the oras package to ghcr
      id-token: write  # Required for attestation signing
      attestations: write  # Required to create attestations
      artifact-metadata: write  # Required by actions/attest to write attestation metadata
    outputs:
      qcow2_oras_image: ${{ steps.publish_oras_qcow2.outputs.image }}:${{ steps.publish_oras_qcow2.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: "${{ inputs.git_ref }}"
          allow-unsafe-pr-checkout: true

      # Required by rootless mkosi
      - name: Un-restrict user namespaces
        if: inputs.arch == 'amd64'
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Rebase the code
        if: github.event_name == 'pull_request_target'
        working-directory: ./
        run: |
          ./hack/ci-helper.sh rebase-atop-of-the-latest-target-branch

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Login to quay Container Registry
        if: ${{ startsWith(inputs.registry, 'quay.io') }}
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: quay.io
          username: ${{ vars.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Login to the ghcr Container registry
        if: ${{ startsWith(inputs.registry, 'ghcr.io') }}
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            alien \
            bubblewrap \
            dnf \
            qemu-utils \
            uidmap
          # yq may be pre-installed on self-hosted runners
          command -v yq || sudo snap install yq
          yq --version | grep -qE 'v4\.[0-9]+' || { echo "yq version is not 4.x, please install yq 4.x"; exit 1; }

      - name: Read properties from versions.yaml
        run: |
          echo "MKOSI_VERSION=$(yq -e '.tools.mkosi' versions.yaml)" >> "$GITHUB_ENV"
          echo "ORAS_VERSION=$(yq -e '.tools.oras' versions.yaml)" >> "$GITHUB_ENV"

      - uses: oras-project/setup-oras@1d808f7d7f6995cc68b7bf507bfe5c5446e1dc9d # v2.0.1
        with:
          version: ${{ env.ORAS_VERSION }}

      - name: Build binaries
        id: build_binaries
        working-directory: src/cloud-api-adaptor/podvm
        run: make podvm-binaries
        env:
          ARCH: ${{ inputs.arch }}
          VERIFY_PROVENANCE: yes

      - name: Build mkosi debug image
        if: ${{ inputs.debug == true }}
        working-directory: src/cloud-api-adaptor/podvm
        run: make image-debug
        env:
          MKOSI_VERSION: ${{ env.MKOSI_VERSION }}

      - name: Build mkosi image
        if: ${{ inputs.debug == false }}
        working-directory: src/cloud-api-adaptor/podvm
        run: make image
        env:
          MKOSI_VERSION: ${{ env.MKOSI_VERSION }}

      - name: Upload the qcow2 with oras
        id: publish_oras_qcow2
        working-directory: src/cloud-api-adaptor/podvm
        run: |
          mkdir oras
          cd oras
          cp ../build/podvm-*.qcow2 .
          tar cJf podvm.tar.xz podvm-*.qcow2
          image=${REGISTRY}/podvm-generic-ubuntu
          if [ "${DEBUG}" = "true" ]; then
            image=${image}-debug
          fi
          image=${image}-${ARCH}
          tag=$(git rev-parse --short HEAD)
          oras push "${image}:${tag}" podvm.tar.xz

          # If the input has a different image-tag then also push it with that tag
          if [ -n "${IMAGE_TAG}" ] && [ "${IMAGE_TAG}" != "${tag}" ];then
            oras push "${image}:${IMAGE_TAG}" podvm.tar.xz
          fi

          # add image and digest to output for attestation
          echo "image=${image}" >> "$GITHUB_OUTPUT"
          digest="$(oras manifest fetch "${image}:${tag}" --descriptor | jq -r .digest)"
          echo "digest=${digest}" >> "$GITHUB_OUTPUT"
          echo "tag=${tag}" >> "$GITHUB_OUTPUT"
        env:
          DEBUG: ${{ inputs.debug == true && 'true' || 'false' }}
          REGISTRY: ${{ inputs.registry }}
          ARCH: ${{ inputs.arch }}
          IMAGE_TAG: ${{ inputs.image_tag }}

      - uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-name: ${{ steps.publish_oras_qcow2.outputs.image }}
          subject-digest: ${{ steps.publish_oras_qcow2.outputs.digest }}
          push-to-registry: true
