# (C) Copyright Confidential Containers Contributors 2023.
# SPDX-License-Identifier: Apache-2.0
#
# Build and push project images on pull requests merged.
---
name: Publish project images

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  caa:
    uses: ./.github/workflows/caa_build_and_push_per_arch.yaml
    with:
      git_ref: ${{ github.sha }}
    secrets: inherit

  csi-wrapper:
    uses: ./.github/workflows/csi_wrapper_images.yaml
    with:
      image_tags: latest,${{ github.sha }}
      git_ref: ${{ github.sha }}
    secrets: inherit

  peerpod-ctrl:
    uses: ./.github/workflows/peerpod-ctrl_image.yaml
    with:
      image_tags: latest,${{ github.sha }}
      git_ref: ${{ github.sha }}
    secrets: inherit

  peerpodconfig-ctrl:
    uses: ./.github/workflows/peerpodconfig-ctrl_image.yaml
    with:
      image_tags: ${{ github.sha }},latest
      git_ref: ${{ github.sha }}
    secrets: inherit

  webhook:
    uses: ./.github/workflows/webhook_image.yaml
    with:
      image_tags: ${{ github.sha }},latest
      git_ref: ${{ github.sha }}
    secrets: inherit
