# Copyright Confidential Containers Contributors
# SPDX-License-Identifier: Apache-2.0
#
# Build and push the project release images.
---
name: Release project images
on:
  release:
    types: [created]

permissions: {}

jobs:
  caa:
    uses: ./.github/workflows/caa_build_and_push_all_arches.yaml
    with:
      dev_tags: ${{ github.event.release.tag_name }}-dev
      release_tags: ${{ github.event.release.tag_name }}
      git_ref: ${{ github.ref }}
    permissions:
      contents: read
      packages: write
    secrets:
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

  csi-wrapper:
    uses: ./.github/workflows/csi_wrapper_images.yaml
    with:
      image_tags: ${{ github.event.release.tag_name }}
      git_ref: ${{ github.ref }}
    permissions:
      contents: read
      packages: write
    secrets:
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

  peerpod-ctrl:
    uses: ./.github/workflows/peerpod-ctrl_image.yaml
    with:
      image_tags: ${{ github.event.release.tag_name }}
      git_ref: ${{ github.ref }}
    permissions:
      packages: write  # Required for pushing to GitHub Container Registry
    secrets:
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

  podvm-images:
    uses: ./.github/workflows/podvm_publish.yaml
    with:
      git_ref: ${{ github.ref }}
      image_tag: ${{ github.event.release.tag_name }}
    permissions:
      contents: read           # Required for checkout
      packages: write          # Required for pushing to GitHub Container Registry
      id-token: write          # Required for attestation signing
      attestations: write      # Required for persisting attestations
      artifact-metadata: write # Required by podvm_mkosi.yaml to write attestation metadata
    secrets:
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

  webhook:
    uses: ./.github/workflows/webhook_image.yaml
    with:
      image_tags: ${{ github.event.release.tag_name }}
      git_ref: ${{ github.ref }}
    permissions:
      contents: read
      packages: write
    secrets:
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

  peerpods-chart:
    uses: ./.github/workflows/peerpods-chart_image.yaml
    with:
      git_ref: ${{ github.event.release.tag_name }}
    permissions:
      contents: read       # Required for checkout
      packages: write      # Required for pushing to GitHub Container Registry
      id-token: write      # Required for attestation signing
      attestations: write  # Required for persisting attestations
      artifact-metadata: write  # Required by actions/attest
