# Copyright Confidential Containers Contributors
# SPDX-License-Identifier: Apache-2.0
#
# Run end-to-end tests if any webhook source files changed.
---
name: webhook-test

on:
  push:
    branches:
      - 'main'
    paths:
      - 'webhook/**'
  pull_request:
    paths:
      - 'webhook/**'

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webhook
    steps:
      - name: Checkout the pull request code
        uses: actions/checkout@v3
      - name: Read properties from versions.yaml
        run: |
          go_version="$(yq '.tools.golang' ../versions.yaml)"
          [ -n "$go_version" ]
          echo "GO_VERSION=${go_version}" >> "$GITHUB_ENV"
      - name: Setup Golang version ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Install kind
        run: |
          go install sigs.k8s.io/kind@v0.16.0
      - name: Install bats
        run: |
          git clone https://github.com/bats-core/bats-core.git
          cd bats-core
          ./install.sh ~/.local
      - name: Verify go modules and manifests
        run: make verify
      - name: Run end-to-end tests
        run: |
          make test-e2e
