resources:
- manifests.yaml
- service.yaml

configurations:
- kustomizeconfig.yaml

patches:
- path: namespace_selector_patch.yaml
- patch: |-
    - op: add
      path: /webhooks/0/rules/0/scope
      value: Namespaced
  target:
    kind: MutatingWebhookConfiguration
